#!/bin/sh
# autopkgtest check: Run the installed-tests to verify pango works correctly
# (C) 2013 Canonical Ltd.
# Author: Iain Lane <iain.lane@canonical.com>

set -e

export XDG_RUNTIME_DIR="$AUTOPKGTEST_TMP"

debian/tests/run-with-locales \
	--generate en_US.utf8 \
	-- \
env \
	LC_ALL=en_US.utf8 \
dbus-run-session -- \
xvfb-run -a \
gnome-desktop-testing-runner pango
